---
name: "Login to ACR"
description: "Login to ACR"
inputs:
  azure-credentials:
    description: "Azure credentials"
    required: true
  registry:
    description: "Target container registry to push the tag to"
    required: true
  registry-username:
    description: "Target container registry username"
    required: true
  registry-password:
    description: "Target container registry users password"
    required: true


runs:
  using: "composite"
  steps:
    - name: Login via Azure CLI
      uses: azure/login@v1.4.6
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

