name: debug1
"on": workflow_dispatch
jobs:
  issue_245:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: debug
      - run: npm ci
      - run: npm run build
      - uses: ./
      - name: Create Pull Request
        uses: fredfrazao/GitHub-Actions/actions/create-or-update-pull-request-action@master
        id: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "title"
          body: "[body"
          branch: "ff_test"
          path: "/"
          commit-message: "test commit msg"
