name: debug1
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: fredfrazao/GitHub-Actions/actions/create-or-update-pull-request-action@v1.0.0
        id: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "title"
          body: "[body"
          branch: "ff_test"
          path: "/"
          commit-message: "test commit msg"
