---
name: Lint
on:
 pull_request_target:
  types:
   - opened
   - edited
   - synchronize
 pull_request:
  branches:
   - main


jobs:
 lint-pr-title:
  name: Validate PR title
  runs-on: ubuntu-20.04
  steps:
   - uses: amannn/action-semantic-pull-request@v5.0.2
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 lint-files:
  name: Lint YAML files
  runs-on: ubuntu-20.04
  steps:
   - name: Checkout
     uses: actions/checkout@v3
   - name: Lint all files
     shell: bash
     run: |
      pip install yamllint
      yamllint -d "{extends: relaxed, rules: {line-length: {max: 250}}}" .
