
name: open pr
on:
  workflow_dispatch:


jobs:
  lint-files:
    name: List pull request titles
    runs-on: ubuntu-20.04
    steps:

      - name: List pull request titles
        id: list-poc-data
        uses: jkisk/list-open-pulls@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
      - name: Check output
        run: echo ${{ steps.list-poc-data.outputs.titles }}

      - uses: zrosenbauer/action-slack@main
        if: needs.steps.list-poc-data.outputs != '[]'
        with:
          username: "PullRequestReminder"
          icon_emoji: ":rocket:"
          text: |
             :boom:`There are some Open Pull Request on ${{ github.repository }}, please check them`

          webhook_url: https://hooks.slack.com/services/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
